### ISSUE TITLE
Feature request: record client specific metadata

### ISSUE THREAD

**Issue by ptitzler** [IBM-Bluemix/cf-deployment-tracker-service#1]
The tracker service currently records tracking request date, application name, application version, application URIs, repository URL, space ID and code version. Initially we had only one tracker client (for nodejs) but we are gradually adding other clients (e.g. for Java). It might be useful to track additional metadata about the client itself, such as the implementation language to allow for more granular analysis.

**Comment by ptitzler** [comment]
The tracker service should accept two (optional) payload properties: 
* `runtime` - a singleton value (e.g. nodejs, java, ...) that identifies the sample application's runtime environment. 
* `bound_vcap_services` - an array (e.g. ['cloudantNoSQLDB','dashDB']) that identifies what services have been bound to the app.
We want to use this information to classify the sample applications.

**Comment by bradley-holt** [comment]
+1 from me. What do you think, @jsloyer?

**Comment by ptitzler** [comment]
We need to also track how many instances of a particular service are bound. While there is probably just one instance in the majority of use-case scenarios, there are some that are some that are more likely to use multiple instances of the same service:
 * on-premises data sources (accessible using user-provided services)
 * data movement across from a source to a target (that are, for example, in different geographic locations)

**Comment by ptitzler** [comment]
Updated spec proposal for service bindings:

Add code to the server to accept an optional payload if _at least one_ service instance is bound to the tracked application: `{ bound_vcap_services : [ {<service>: <service_instance_count> }] }`.

&lt;service&gt; is the service's label (e.g. cloudantNoSQLDB) and &lt;service_instance_count&gt; the number of service instances that are bound to the app.
If no service instance is bound to an application the `bound_vcap_services` property is not persisted in the Cloudant repository.

Example: `{ bound_vcap_services : [ {'cloudantNoSQLDB': 2 }, {'rediscloud': 1 }] }`

**Comment by ptitzler** [comment]
To make the payload processing more future-proof, we might want to use a more verbose format:  
`{ "bound_vcap_services" : [ {"cloudantNoSQLDB": {"count":2} }, {"rediscloud": {"count":1} }] }`

**Comment by jsloyer** [comment]
@ptitzler do we really need to do this? we can look up info about the users app in our dashdb to get this info...

**Comment by bradley-holt** [comment]
@jsloyer: I think it's valuable to have this data collected directly by the Deployment Tracker Service. This makes analysis a bit easier, as you don't have the extra step of going to look this up in Bluemix. Also, if we think about the Deployment Tracker Service as a standalone tool that would be useful to people outside of IBM, this proposed feature would be the _only_ way for them to get at this data.

**Comment by jsloyer** [comment]
@bradley-holt while i agree it makes current deployments easier, we are missing this info for all the stored deployments so far.

**Comment by bradley-holt** [comment]
@jsloyer: I think that's OK. As long as the schema is backwards compatible, I don't seen an issue with adding fields to the schema. If we had accepted this as a constraint when the application was first built, then it would have taken longer to get the first release out as we would have worried about having the data model perfect and complete at the very beginning. We can't (and shouldn't) predict all of our needs upfront. Adding more data collection as we move forward is perfectly OK in my mind. We just need to know that any data before a certain point in time won't have this level of detail.

**Comment by jsloyer** [comment]
@bradley-holt ok im fine thne... we can move forward with this.

**Comment by bradley-holt** [comment]
@ptitzler What about the following data structure instead?

```json
{
  "bound_vcap_services": {
    "cloudantNoSQLDB": {
      "count": 2
    },
    "rediscloud": {
      "count": 1
    }
  }
}
```

My thinking behind this:

* Object keys on `bound_vcap_services` will be much easier to find programmatically than searching through values in an array.
* Service instances are uniquely named. If service instances aren't uniquely named, then we can't tell the difference anyways, so `¯\_(ツ)_/¯`.
* I agree with you about the `count` being nested in an object so that we leave room for the collection of other metadata in the future.

**Comment by ptitzler** [comment]
Works for me!

**Comment by ptitzler** [comment]
Delivered by PR #8
