### ISSUE TITLE
Use Cloudant Lite plan instead of Shared

### ISSUE THREAD

**Issue by l2fprod** [IBM-Bluemix/cf-deployment-tracker-service#203]
This repo uses Cloudant Shared plan. This plan has been deprecated and is no longer available. An alternative is to use the Lite plan.

https://www.ibm.com/blogs/bluemix/2016/09/new-cloudant-lite-standard-plans-are-live-in-bluemix-public/

**Comment by ptitzler** [comment]
We'll update the service plan prereq in `manifest.yml` to `Lite` to allow for demo deployment without a PAYG Bluemix account. This plan is free but should not be used in production deployments due to the restrictions it imposes on storage and throughput.

**Comment by ptitzler** [comment]
Delivered by #212
