### ISSUE TITLE
Determine if there is a way to disable Github cache of deployment tracker badges

### ISSUE THREAD

**Issue by tfrank64** [IBM-Bluemix/cf-deployment-tracker-service#209]
The problem is our 2 bluemix deployment badges have deployment counts that quickly become out of sync because of the automatic caching that Github utilizes. Our badges were just updated, but as time goes on, they should become out of sync again in our [repo](https://github.com/IBM-Bluemix/Kitura-Starter)

It seems others have run into their images not updating https://github.com/github/markup/issues/224
Is there any way to set the image assets/badges we need to have `Cache-Control: no-cache` header value?

**Comment by ptitzler** [comment]
Currently we are only setting the `Etag` header when a request to the `/stats/:hash/badge.svg` and `/stats/:hash/button.svg` enpoints is made. To prevent caching we should also set `Expires` (`0`) and `Cache-Control` (`no-cache`) headers as recommended in above reference.

**Comment by ptitzler** [comment]
Delivered and deployed by #210
