### ISSUE TITLE
Improve handling of tracking requests that are associated with multiple application instances

### ISSUE THREAD

**Issue by ptitzler** [IBM-Bluemix/cf-deployment-tracker-service#228]
Users can start multiple instances of the same application. Depending on its implementation, Deployment Tracker clients might send multiple tracking requests, which need to be de-duplicated  (only store tracking requests if `VCAP_APPLICATION.instance_index` is `0`) or turned into unique requests (by storing the `VCAP_APPLICATION.instance_index`). 

Example: User starts application with 2 instances. `VCAP_APPLICATION` is set by CloudFoundry to
`{application_id":"39908504-6124-4c1c-bbb8-70a2017754b1","instance_index":0, ...}` and
`{application_id":"39908504-6124-4c1c-bbb8-70a2017754b1","instance_index":1, ...}`.

**Comment by bradley-holt** [comment]
@ptitzler: My suggestion would be to continue to track all events, yet add this additional `instance_index` metadata so that we can de-duplicate during the analysis phase.

**Comment by ptitzler** [comment]
I agree. This additional information might be useful at some point in the future.

**Comment by ptitzler** [comment]
Delivered by #229
